### PR TITLE
CI: sync with openwrt/packages, update fallback build packages

### PR DESCRIPTION
**Pull request by jefferyto**
This is all CI changes cherry picked from the packages feed (except https://github.com/openwrt/packages/commit/7b7265293f953c71a65099ecbdbfbaf5f14bf4f8 and the revert https://github.com/openwrt/packages/commit/489cffadd27b84351136d06bcb5ddd5a7eec81a8), plus one change to set the fallback build packages to packages in this feed (instead of packages from the packages feed).

### CODE REVIEW

**Comment by jefferyto** [comment]
I believe mesa is failing to compile because mako is installed for host Python (in `$(STAGING_DIR_HOSTPKG)`) but meson is configured to use build host Python (in `$(STAGING_DIR_HOST)`), so it does not see / cannot access mako. I'm not really sure how to fix this.

**Comment by esaaprillia** [comment]
> I believe mesa is failing to compile because mako is installed for host Python (in `$(STAGING_DIR_HOSTPKG)`) but meson is configured to use build host Python (in `$(STAGING_DIR_HOST)`), so it does not see / cannot access mako. I'm not really sure how to fix this.

maybe this is the cause

https://github.com/openwrt/openwrt/blob/076f945dfbc8afa6ced7c5f67d95ab27383dd1e4/include/meson.mk#L68

https://github.com/openwrt/openwrt/blob/076f945dfbc8afa6ced7c5f67d95ab27383dd1e4/include/meson.mk#L87

**Comment by esaaprillia** [comment]
@jefferyto 

Mesa can be built by adding this

```
define Meson/CreateNativeFile
	$(STAGING_DIR_HOST)/bin/sed \
		-e "s|@CC@|$(foreach BIN,$(HOSTCC),'$(BIN)',)|" \
		-e "s|@CXX@|$(foreach BIN,$(HOSTCXX),'$(BIN)',)|" \
		-e "s|@PKGCONFIG@|$(PKG_CONFIG)|" \
		-e "s|@CMAKE@|$(STAGING_DIR_HOST)/bin/cmake|" \
		-e "s|@PYTHON@|$(STAGING_DIR_HOSTPKG)/bin/python3|" \
		-e "s|@CFLAGS@|$(foreach FLAG,$(HOST_CFLAGS) $(HOST_CPPFLAGS),'$(FLAG)',)|" \
		-e "s|@CXXFLAGS@|$(foreach FLAG,$(HOST_CXXFLAGS) $(HOST_CPPFLAGS),'$(FLAG)',)|" \
		-e "s|@LDFLAGS@|$(foreach FLAG,$(HOST_LDFLAGS),'$(FLAG)',)|" \
		-e "s|@PREFIX@|$(HOST_BUILD_PREFIX)|" \
		< $(MESON_DIR)/openwrt-native.txt.in \
		> $(1)
endef

define Meson/CreateCrossFile
	$(STAGING_DIR_HOST)/bin/sed \
		-e "s|@CC@|$(foreach BIN,$(TARGET_CC),'$(BIN)',)|" \
		-e "s|@CXX@|$(foreach BIN,$(TARGET_CXX),'$(BIN)',)|" \
		-e "s|@LD@|$(foreach FLAG,$(TARGET_LINKER),'$(FLAG)',)|" \
		-e "s|@AR@|$(TARGET_AR)|" \
		-e "s|@STRIP@|$(TARGET_CROSS)strip|" \
		-e "s|@NM@|$(TARGET_NM)|" \
		-e "s|@PKGCONFIG@|$(PKG_CONFIG)|" \
		-e "s|@CMAKE@|$(STAGING_DIR_HOST)/bin/cmake|" \
		-e "s|@PYTHON@|$(STAGING_DIR_HOSTPKG)/bin/python3|" \
		-e "s|@CFLAGS@|$(foreach FLAG,$(TARGET_CFLAGS) $(EXTRA_CFLAGS) $(TARGET_CPPFLAGS) $(EXTRA_CPPFLAGS),'$(FLAG)',)|" \
		-e "s|@CXXFLAGS@|$(foreach FLAG,$(TARGET_CXXFLAGS) $(EXTRA_CXXFLAGS) $(TARGET_CPPFLAGS) $(EXTRA_CPPFLAGS),'$(FLAG)',)|" \
		-e "s|@LDFLAGS@|$(foreach FLAG,$(TARGET_LDFLAGS) $(EXTRA_LDFLAGS),'$(FLAG)',)|" \
		-e "s|@ARCH@|$(MESON_ARCH)|" \
		-e "s|@CPU@|$(MESON_CPU)|" \
		-e "s|@ENDIAN@|$(if $(CONFIG_BIG_ENDIAN),big,little)|" \
		< $(MESON_DIR)/openwrt-cross.txt.in \
		> $(1)
endef
```

**Comment by Ansuel** [comment]
@jefferyto Closing this. I migrated to a centralized place where the actions are shared. Thanks a lot for the work tho.

**Pull request closed without merging**
